"""initial schema

Revision ID: febfd647fd64
Revises: 
Create Date: 2026-09-10 16:59:16.498452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febfd647fd64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('import_runs',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('raw_response_hash', sa.String(length=64), nullable=True),
    sa.Column('is_synthetic_fixture', sa.Boolean(), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'delivery_date', 'revision', name='uq_import_run_revision')
    )
    op.create_index(op.f('ix_import_runs_delivery_date'), 'import_runs', ['delivery_date'], unique=False)
    op.create_table('invitations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_organization_id'), 'invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.create_table('memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership_user_org')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('csrf_secret', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('stations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_organization_id'), 'stations', ['organization_id'], unique=False)
    op.create_table('alerts',
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_station_id'), 'alerts', ['station_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_station_id'), 'audit_logs', ['station_id'], unique=False)
    op.create_table('consumption_forecasts',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('base_load_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('ev_component_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('flexible_component_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('is_cold_start', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_forecasts_interval_start'), 'consumption_forecasts', ['interval_start'], unique=False)
    op.create_index(op.f('ix_consumption_forecasts_issued_at'), 'consumption_forecasts', ['issued_at'], unique=False)
    op.create_index(op.f('ix_consumption_forecasts_station_id'), 'consumption_forecasts', ['station_id'], unique=False)
    op.create_table('devices',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_boot_id', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_station_id'), 'devices', ['station_id'], unique=False)
    op.create_table('market_price_intervals',
    sa.Column('import_run_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('interval_index', sa.Integer(), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('price_lei_per_mwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price_lei_per_kwh', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('is_negative', sa.Boolean(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'delivery_date', 'interval_start', 'revision', name='uq_market_price_interval')
    )
    op.create_index(op.f('ix_market_price_intervals_delivery_date'), 'market_price_intervals', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_market_price_intervals_import_run_id'), 'market_price_intervals', ['import_run_id'], unique=False)
    op.create_index(op.f('ix_market_price_intervals_interval_start'), 'market_price_intervals', ['interval_start'], unique=False)
    op.create_table('preference_versions',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('min_reserve_soc_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_normal_soc_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_optimization_energy_kwh', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('allow_grid_charge', sa.Boolean(), nullable=False),
    sa.Column('allow_battery_export', sa.Boolean(), nullable=False),
    sa.Column('max_efc_per_day', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('max_efc_per_month', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('soc_targets', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=24), nullable=False),
    sa.Column('ev_required_energy_kwh', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('ev_departure_time', sa.Time(), nullable=True),
    sa.Column('automation_suspended_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arbitrage_min_benefit_lei', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('conflict_warnings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'version', name='uq_preference_version')
    )
    op.create_index(op.f('ix_preference_versions_station_id'), 'preference_versions', ['station_id'], unique=False)
    op.create_table('station_config_versions',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('pv_installed_power_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('inverter_power_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('battery_reference_capacity_kwh', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('battery_available_capacity_kwh', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('battery_max_charge_power_kw', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('battery_max_discharge_power_kw', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('battery_charge_efficiency', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('battery_discharge_efficiency', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('grid_import_limit_kw', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('grid_export_limit_kw', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('ev_enabled', sa.Boolean(), nullable=False),
    sa.Column('ev_battery_capacity_kwh', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('ev_max_charge_power_kw', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'version', name='uq_station_config_version')
    )
    op.create_index(op.f('ix_station_config_versions_station_id'), 'station_config_versions', ['station_id'], unique=False)
    op.create_table('tariffs',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_station_id'), 'tariffs', ['station_id'], unique=False)
    op.create_table('telemetry_aggregates',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pv_energy_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('load_energy_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('battery_charge_energy_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('battery_discharge_energy_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grid_import_energy_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grid_export_energy_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ev_energy_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('avg_battery_soc_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'period_type', 'period_start', name='uq_telemetry_aggregate_period')
    )
    op.create_index(op.f('ix_telemetry_aggregates_period_start'), 'telemetry_aggregates', ['period_start'], unique=False)
    op.create_index(op.f('ix_telemetry_aggregates_station_id'), 'telemetry_aggregates', ['station_id'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('ghi_w_m2', sa.Float(), nullable=True),
    sa.Column('dni_w_m2', sa.Float(), nullable=True),
    sa.Column('dhi_w_m2', sa.Float(), nullable=True),
    sa.Column('cloud_cover_percent', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecasts_interval_start'), 'weather_forecasts', ['interval_start'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_issued_at'), 'weather_forecasts', ['issued_at'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_station_id'), 'weather_forecasts', ['station_id'], unique=False)
    op.create_table('claim_codes',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('code_prefix', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_device_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claimed_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_codes_code_hash'), 'claim_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_claim_codes_station_id'), 'claim_codes', ['station_id'], unique=False)
    op.create_table('device_credentials',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('secret_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_ip', sa.String(length=64), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_credentials_device_id'), 'device_credentials', ['device_id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('horizon_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('station_config_version_id', sa.Uuid(), nullable=True),
    sa.Column('preference_version_id', sa.Uuid(), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('solver_name', sa.String(length=32), nullable=False),
    sa.Column('solver_status', sa.String(length=32), nullable=True),
    sa.Column('objective_value_lei', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solver_timeout_seconds', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('triggered_by', sa.String(length=24), nullable=False),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('explanation_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preference_version_id'], ['preference_versions.id'], ),
    sa.ForeignKeyConstraint(['station_config_version_id'], ['station_config_versions.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_station_id'), 'optimization_runs', ['station_id'], unique=False)
    op.create_table('panel_groups',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('config_version_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('power_kwp', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('azimuth_degrees', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('tilt_degrees', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_version_id'], ['station_config_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panel_groups_config_version_id'), 'panel_groups', ['config_version_id'], unique=False)
    op.create_index(op.f('ix_panel_groups_station_id'), 'panel_groups', ['station_id'], unique=False)
    op.create_table('pv_forecasts',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('based_on_weather_forecast_id', sa.Uuid(), nullable=True),
    sa.Column('predicted_power_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('scenario', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['based_on_weather_forecast_id'], ['weather_forecasts.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pv_forecasts_interval_start'), 'pv_forecasts', ['interval_start'], unique=False)
    op.create_index(op.f('ix_pv_forecasts_issued_at'), 'pv_forecasts', ['issued_at'], unique=False)
    op.create_index(op.f('ix_pv_forecasts_station_id'), 'pv_forecasts', ['station_id'], unique=False)
    op.create_table('tariff_versions',
    sa.Column('tariff_id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fixed_price_lei_per_kwh', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('opcom_margin_lei_per_kwh', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('fixed_monthly_fee_lei', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('variable_component_lei_per_kwh', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('settlement_method', sa.String(length=64), nullable=False),
    sa.Column('settlement_interval_days', sa.Integer(), nullable=False),
    sa.Column('economic_calculation_disabled', sa.Boolean(), nullable=False),
    sa.Column('limitation_note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_versions_tariff_id'), 'tariff_versions', ['tariff_id'], unique=False)
    op.create_table('telemetry_raw',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('boot_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pv_power_w', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('load_power_w', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('battery_power_w', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('grid_power_w', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('battery_soc_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ev_connected', sa.Boolean(), nullable=True),
    sa.Column('ev_power_w', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'boot_id', 'sequence', name='uq_telemetry_dedup')
    )
    op.create_index(op.f('ix_telemetry_raw_device_id'), 'telemetry_raw', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_raw_measured_at'), 'telemetry_raw', ['measured_at'], unique=False)
    op.create_index(op.f('ix_telemetry_raw_station_id'), 'telemetry_raw', ['station_id'], unique=False)
    op.create_table('plans',
    sa.Column('optimization_run_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_device_id', sa.Uuid(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_plan_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'version', name='uq_plan_station_version')
    )
    op.create_index(op.f('ix_plans_optimization_run_id'), 'plans', ['optimization_run_id'], unique=True)
    op.create_index(op.f('ix_plans_station_id'), 'plans', ['station_id'], unique=False)
    op.create_table('plan_intervals',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pv_forecast_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('load_forecast_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('battery_power_target_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('grid_power_target_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('battery_soc_target_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ev_charge_power_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('price_import_lei_kwh', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('price_export_lei_kwh', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('observed_battery_power_kw', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('observed_grid_power_kw', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('observed_soc_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('deviation_notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'interval_start', name='uq_plan_interval_start')
    )
    op.create_index(op.f('ix_plan_intervals_plan_id'), 'plan_intervals', ['plan_id'], unique=False)
    op.create_table('commands',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('plan_interval_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('author', sa.String(length=24), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_interval_id'], ['plan_intervals.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'idempotency_key', name='uq_command_idempotency')
    )
    op.create_index(op.f('ix_commands_device_id'), 'commands', ['device_id'], unique=False)
    op.create_index(op.f('ix_commands_plan_interval_id'), 'commands', ['plan_interval_id'], unique=False)
    op.create_index(op.f('ix_commands_station_id'), 'commands', ['station_id'], unique=False)
    op.create_table('command_events',
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_events_command_id'), 'command_events', ['command_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_events_command_id'), table_name='command_events')
    op.drop_table('command_events')
    op.drop_index(op.f('ix_commands_station_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_plan_interval_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_device_id'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_plan_intervals_plan_id'), table_name='plan_intervals')
    op.drop_table('plan_intervals')
    op.drop_index(op.f('ix_plans_station_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_optimization_run_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_telemetry_raw_station_id'), table_name='telemetry_raw')
    op.drop_index(op.f('ix_telemetry_raw_measured_at'), table_name='telemetry_raw')
    op.drop_index(op.f('ix_telemetry_raw_device_id'), table_name='telemetry_raw')
    op.drop_table('telemetry_raw')
    op.drop_index(op.f('ix_tariff_versions_tariff_id'), table_name='tariff_versions')
    op.drop_table('tariff_versions')
    op.drop_index(op.f('ix_pv_forecasts_station_id'), table_name='pv_forecasts')
    op.drop_index(op.f('ix_pv_forecasts_issued_at'), table_name='pv_forecasts')
    op.drop_index(op.f('ix_pv_forecasts_interval_start'), table_name='pv_forecasts')
    op.drop_table('pv_forecasts')
    op.drop_index(op.f('ix_panel_groups_station_id'), table_name='panel_groups')
    op.drop_index(op.f('ix_panel_groups_config_version_id'), table_name='panel_groups')
    op.drop_table('panel_groups')
    op.drop_index(op.f('ix_optimization_runs_station_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_device_credentials_device_id'), table_name='device_credentials')
    op.drop_table('device_credentials')
    op.drop_index(op.f('ix_claim_codes_station_id'), table_name='claim_codes')
    op.drop_index(op.f('ix_claim_codes_code_hash'), table_name='claim_codes')
    op.drop_table('claim_codes')
    op.drop_index(op.f('ix_weather_forecasts_station_id'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_issued_at'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_interval_start'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index(op.f('ix_telemetry_aggregates_station_id'), table_name='telemetry_aggregates')
    op.drop_index(op.f('ix_telemetry_aggregates_period_start'), table_name='telemetry_aggregates')
    op.drop_table('telemetry_aggregates')
    op.drop_index(op.f('ix_tariffs_station_id'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_station_config_versions_station_id'), table_name='station_config_versions')
    op.drop_table('station_config_versions')
    op.drop_index(op.f('ix_preference_versions_station_id'), table_name='preference_versions')
    op.drop_table('preference_versions')
    op.drop_index(op.f('ix_market_price_intervals_interval_start'), table_name='market_price_intervals')
    op.drop_index(op.f('ix_market_price_intervals_import_run_id'), table_name='market_price_intervals')
    op.drop_index(op.f('ix_market_price_intervals_delivery_date'), table_name='market_price_intervals')
    op.drop_table('market_price_intervals')
    op.drop_index(op.f('ix_devices_station_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_consumption_forecasts_station_id'), table_name='consumption_forecasts')
    op.drop_index(op.f('ix_consumption_forecasts_issued_at'), table_name='consumption_forecasts')
    op.drop_index(op.f('ix_consumption_forecasts_interval_start'), table_name='consumption_forecasts')
    op.drop_table('consumption_forecasts')
    op.drop_index(op.f('ix_audit_logs_station_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_station_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_stations_organization_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_organization_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_import_runs_delivery_date'), table_name='import_runs')
    op.drop_table('import_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
