/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/mobile/charging-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Charging Sessions */
        get: operations["charging_sessions_api_v1_mobile_charging_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobile/charts/energy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chart
         * @description Energy sums and mean SOC from retained rollups; maximum 768 buckets, no raw samples.
         */
        get: operations["chart_api_v1_mobile_charts_energy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobile/home-assistant/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Context */
        get: operations["context_api_v1_mobile_home_assistant_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobile/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications */
        get: operations["notifications_api_v1_mobile_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mobile/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Single first-screen read. Optional station_id auto-selects only a sole accessible station.
         */
        get: operations["overview_api_v1_mobile_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** MobileChargingSession */
        MobileChargingSession: {
            /**
             * Connector Id
             * Format: uuid
             */
            connector_id: string;
            /** Ended At */
            ended_at: string | null;
            energy: components["schemas"]["MobileMetric"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** State */
            state: string;
            /** Vehicle Id */
            vehicle_id: string | null;
        };
        /** MobileChargingSessions */
        MobileChargingSessions: {
            /** Items */
            items: components["schemas"]["MobileChargingSession"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Station Id
             * Format: uuid
             */
            station_id: string;
        };
        /** MobileChart */
        MobileChart: {
            /** Aggregation */
            aggregation: {
                [key: string]: string;
            };
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Measured At */
            measured_at?: string | null;
            /** Points */
            points: components["schemas"]["MobileChartPoint"][];
            /** Received At */
            received_at?: string | null;
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "15m" | "1h" | "1d";
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Source
             * @default telemetry_aggregate
             */
            source: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * Station Id
             * Format: uuid
             */
            station_id: string;
            /** Timezone */
            timezone: string;
            /** Units */
            units: {
                [key: string]: string;
            };
        };
        /** MobileChartPoint */
        MobileChartPoint: {
            /** Coverage */
            coverage: {
                [key: string]: string;
            };
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Quality
             * @enum {string}
             */
            quality: "measured" | "estimated" | "declared" | "simulated" | "stale" | "partial" | "missing" | "unknown";
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Updated At */
            updated_at: string | null;
            /** Values */
            values: {
                [key: string]: string | null;
            };
        };
        /** MobileComparison */
        MobileComparison: {
            /** Delta */
            delta: string;
            /** Delta Percent */
            delta_percent: string | null;
            /** Previous Value */
            previous_value: string;
            /**
             * Quality
             * @enum {string}
             */
            quality: "measured" | "estimated" | "declared" | "simulated" | "stale" | "partial" | "missing" | "unknown";
        };
        /** MobileCost */
        MobileCost: {
            /**
             * Currency
             * @default RON
             * @constant
             */
            currency: "RON";
            /** Excludes */
            excludes?: string[];
            /**
             * Method
             * @default historical_hourly_import_minus_export/v1
             */
            method: string;
            net_cost: components["schemas"]["MobileMetric"];
            /** Reason */
            reason: string | null;
            system_benefit: components["schemas"]["MobileMetric"];
        };
        /** MobileDevice */
        MobileDevice: {
            /**
             * Freshness
             * @enum {string}
             */
            freshness: "fresh" | "stale" | "missing";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Heartbeat At */
            last_heartbeat_at: string | null;
            /** Measured At */
            measured_at: string | null;
            /** Name */
            name: string;
            /**
             * Quality
             * @enum {string}
             */
            quality: "measured" | "estimated" | "declared" | "simulated" | "stale" | "partial" | "missing" | "unknown";
            /** Received At */
            received_at: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
        };
        /** MobileEnergyMetric */
        MobileEnergyMetric: {
            comparison?: components["schemas"]["MobileComparison"] | null;
            /** Coverage */
            coverage?: string | null;
            /** Flags */
            flags?: string[];
            /** Measured At */
            measured_at?: string | null;
            /**
             * Quality
             * @enum {string}
             */
            quality: "measured" | "estimated" | "declared" | "simulated" | "stale" | "partial" | "missing" | "unknown";
            /** Received At */
            received_at?: string | null;
            /** Source */
            source: string | null;
            /** Unit */
            unit: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Value */
            value: string | boolean | null;
        };
        /** MobileError */
        MobileError: {
            error: components["schemas"]["MobileIssue"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** MobileForecast */
        MobileForecast: {
            /** Confidence */
            confidence: string | null;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Issued At */
            issued_at: string | null;
            /**
             * Method
             * @default latest_expected_pv_forecast_integral/v1
             */
            method: string;
            pv_energy: components["schemas"]["MobileMetric"];
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** MobileHAContext */
        MobileHAContext: {
            /** Entities */
            entities: components["schemas"]["MobileHAEntity"][];
            /** Insights Consent */
            insights_consent: boolean;
            integration: components["schemas"]["MobileIntegration"];
            /**
             * Physical Control
             * @default false
             * @constant
             */
            physical_control: false;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Station Id
             * Format: uuid
             */
            station_id: string;
            /** Timezone */
            timezone: string;
        };
        /** MobileHAEntity */
        MobileHAEntity: {
            /** Available */
            available: boolean;
            /**
             * Control Authorized
             * @default false
             * @constant
             */
            control_authorized: false;
            /** Entity Id */
            entity_id: string;
            /** Is Simulated */
            is_simulated: boolean;
            /** Is Stale */
            is_stale: boolean;
            /** Kind */
            kind: string;
            /** Mapped Unit */
            mapped_unit: string;
            /** Max Age Seconds */
            max_age_seconds: number;
            metric: components["schemas"]["MobileMetric"];
            /**
             * Source Quality
             * @enum {string}
             */
            source_quality: "measured" | "estimated" | "declared" | "simulated" | "stale" | "partial" | "missing" | "unknown";
        };
        /** MobileIntegration */
        MobileIntegration: {
            /**
             * Available Entities
             * @default 0
             */
            available_entities: number;
            /** Enabled */
            enabled: boolean;
            /**
             * Entity Count
             * @default 0
             */
            entity_count: number;
            /** Issues */
            issues?: components["schemas"]["MobileIssue"][];
            /** Last Seen At */
            last_seen_at: string | null;
            /** Mapping Version */
            mapping_version?: number | null;
            /**
             * Provider
             * @enum {string}
             */
            provider: "deye_cloud" | "home_assistant_bridge" | "home_assistant_mqtt";
            /** Status */
            status: string;
        };
        /** MobileIssue */
        MobileIssue: {
            /**
             * Code
             * @enum {string}
             */
            code: "unauthenticated" | "forbidden" | "no_station" | "station_required" | "integration_disconnected" | "provider_disconnected" | "reauth_required" | "stale" | "rate_limited" | "invalid_request" | "invalid_cursor" | "service_unavailable";
            /** Message */
            message: string;
            /** Resource */
            resource?: string | null;
            /** Retry After Seconds */
            retry_after_seconds?: number | null;
        };
        /** MobileMetric */
        MobileMetric: {
            /** Coverage */
            coverage?: string | null;
            /** Flags */
            flags?: string[];
            /** Measured At */
            measured_at?: string | null;
            /**
             * Quality
             * @enum {string}
             */
            quality: "measured" | "estimated" | "declared" | "simulated" | "stale" | "partial" | "missing" | "unknown";
            /** Received At */
            received_at?: string | null;
            /** Source */
            source: string | null;
            /** Unit */
            unit: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Value */
            value: string | boolean | null;
        };
        /** MobileNotification */
        MobileNotification: {
            /** Body */
            body: string | null;
            /** Category */
            category: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Link */
            link: string | null;
            /** Read At */
            read_at: string | null;
            /** Severity */
            severity: string;
            /** State */
            state: string | null;
            /** Title */
            title: string;
        };
        /** MobileNotifications */
        MobileNotifications: {
            /** Items */
            items: components["schemas"]["MobileNotification"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Station Id
             * Format: uuid
             */
            station_id: string;
            /** Unread Count */
            unread_count: number;
        };
        /** MobileOverview */
        MobileOverview: {
            /** Costs */
            costs: {
                [key: string]: components["schemas"]["MobileCost"];
            };
            /** Energy */
            energy: {
                [key: string]: components["schemas"]["MobilePeriod"];
            };
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
            forecast: components["schemas"]["MobileForecast"];
            /** Integrations */
            integrations: components["schemas"]["MobileIntegration"][];
            /** Issues */
            issues: components["schemas"]["MobileIssue"][];
            /** Live */
            live: {
                [key: string]: components["schemas"]["MobileMetric"];
            };
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            sources: components["schemas"]["MobileSourceSummary"];
            station: components["schemas"]["MobileStation"];
            /** Unread Notifications */
            unread_notifications: number;
        };
        /** MobilePeriod */
        MobilePeriod: {
            /** Comparison Label */
            comparison_label: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["MobileEnergyMetric"];
            };
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** MobileSourceSummary */
        MobileSourceSummary: {
            /** Devices */
            devices: components["schemas"]["MobileDevice"][];
            /** Total Devices */
            total_devices: number;
            /** Truncated */
            truncated: boolean;
        };
        /** MobileStation */
        MobileStation: {
            /**
             * Currency
             * @default RON
             * @constant
             */
            currency: "RON";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Role */
            role: string;
            /** Timezone */
            timezone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    charging_sessions_api_v1_mobile_charging_sessions_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                station_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileChargingSessions"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
        };
    };
    chart_api_v1_mobile_charts_energy_get: {
        parameters: {
            query?: {
                range?: "24h" | "7d" | "30d" | "1y";
                resolution?: ("15m" | "1h" | "1d") | null;
                end?: string | null;
                station_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileChart"];
                };
            };
            /** @description Private chart unchanged after reauthorization */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
        };
    };
    context_api_v1_mobile_home_assistant_context_get: {
        parameters: {
            query?: {
                provider?: "home_assistant_bridge" | "home_assistant_mqtt";
                station_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileHAContext"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
        };
    };
    notifications_api_v1_mobile_notifications_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                unread?: boolean;
                station_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileNotifications"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
        };
    };
    overview_api_v1_mobile_overview_get: {
        parameters: {
            query?: {
                station_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileOverview"];
                };
            };
            /** @description Private representation unchanged after reauthorization */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileError"];
                };
            };
        };
    };
}
